In [1]:
from glob import glob
from os.path import splitext
from os.path import basename
import os
import pandas as pd

In [3]:
editions = []
for edition in glob('./texts_clean/*.txt'):
    editions.append(edition)

In [5]:
editions_metadata = pd.read_csv('./editions.csv', encoding='utf-8', index_col=0)
editions_metadata

,newspaper,year,month,day,link
id,,,,,
1,ahora,1931,4,9,https://hemerotecadigital.bne.es/hd/es/viewer?...
2,ahora,1932,4,15,https://hemerotecadigital.bne.es/hd/es/viewer?...
3,ahora,1932,9,16,https://hemerotecadigital.bne.es/hd/es/viewer?...
4,ahora,1935,1,9,https://hemerotecadigital.bne.es/hd/es/viewer?...
5,ahora,1935,11,15,https://hemerotecadigital.bne.es/hd/es/viewer?...
...,...,...,...,...,...
96,vida socialista,1910,2,20,https://hemerotecadigital.bne.es/hd/es/viewer?...
97,vida socialista,1910,7,24,https://hemerotecadigital.bne.es/hd/es/viewer?...
98,vida socialista,1911,12,17,https://hemerotecadigital.bne.es/hd/es/viewer?...
99,vida socialista,1911,4,16,https://hemerotecadigital.bne.es/hd/es/viewer?...
100,vida socialista,1912,7,14,https://hemerotecadigital.bne.es/hd/es/viewer?...

In [11]:
newspapers = pd.read_csv('./newspapers.csv', encoding='utf-8', index_col=0)
newspapers

,ideology,hq,audience,region,format,hq latitude,hq longitude,foundedin
newspaper,,,,,,,,
ahora,socialist,madrid,adult,national,daily,40.416.775,-3.703.790,1930
andalucia,regionalist,sevilla,adult,andalucia,monthly,37.392.529,-5.994.072,1916
ceda,carlist,madrid,adult,national,biweekly,40400,-3.703.790,1933
el amigo,NaN,madrid,youth,national,daily,40.416.775,-3500,1915
el cantabrico,socialist,santander,adult,cantabria,weekly,43.462.774,-3.805.000,1895
el cruzado espanol,carlist,madrid,adult,national,daily,40500,-3200,1929
el imparcial,liberal,madrid,adult,national,daily,40000,-3.703.790,1867
el pais,republican,madrid,adult,national,daily,404.225.933,-37.054.773,1880
el siglo futuro,carlist,madrid,adult,national,daily,40.416.775,-4,1875
el sol,liberal,madrid,adult,national,daily,40.416.775,-4100,1917
la accion,conservative,madrid,adult,national,daily,40500,-3600,1916
la actualidad,NaN,barcelona,youth,national,weekly,41500,2100,1906
la dinastia,conservative,barcelona,adult,catalonia,daily,41700,2300,1883
las noticias,liberal,barcelona,adult,national,daily,41450,2500,1896
solidaridad obrera,anarchist,barcelona,adult,national,weekly,41.346.176,2700,1907
vida socialista,socialist,madrid,adult,national,weekly,41000,-3.703.790,1910

In [12]:
editions_full = editions_metadata.merge(newspapers, on = "newspaper")
editions_full

,newspaper,year,month,day,link,ideology,hq,audience,region,format,hq latitude,hq longitude,foundedin
0,ahora,1931,4,9,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,daily,40.416.775,-3.703.790,1930
1,ahora,1932,4,15,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,daily,40.416.775,-3.703.790,1930
2,ahora,1932,9,16,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,daily,40.416.775,-3.703.790,1930
3,ahora,1935,1,9,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,daily,40.416.775,-3.703.790,1930
4,ahora,1935,11,15,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,daily,40.416.775,-3.703.790,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,vida socialista,1910,2,20,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,weekly,41000,-3.703.790,1910
96,vida socialista,1910,7,24,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,weekly,41000,-3.703.790,1910
97,vida socialista,1911,12,17,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,weekly,41000,-3.703.790,1910
98,vida socialista,1911,4,16,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,weekly,41000,-3.703.790,1910
99,vida socialista,1912,7,14,https://hemerotecadigital.bne.es/hd/es/viewer?...,socialist,madrid,adult,national,weekly,41000,-3.703.790,1910

In [14]:
def create_subcorpus(feature):
    if not os.path.exists("./stylo/"):
        os.makedirs("./stylo/")
    subcorpus = str("./stylo/" + feature + "/corpus")
    if not os.path.exists(subcorpus):
        os.makedirs(subcorpus)
    for edition in editions:
        edition_id = int(os.path.splitext(basename(edition))[0])
        feature_lookup = str(editions_full.iloc[edition_id-1][feature])
        edition_id = str(edition_id)
        with open(edition, "r") as oldfile, open(subcorpus + "/" + feature_lookup + "_" + edition_id + ".txt", "w") as newfile:
            for line in oldfile:
                newfile.write(line)
        
create_subcorpus("newspaper")
create_subcorpus("ideology")
create_subcorpus("hq")
create_subcorpus("audience")
create_subcorpus("region")
create_subcorpus("format")
create_subcorpus("foundedin")

`os.rename` funtion also works

In [393]:
for filepath in glob('./clean_texts/*.txt'):
    id = int(splitext(basename(filepath))[0])
    os.rename(filepath, edition_list.iloc[id-1]['ideology']+'_'+basename(filepath))

In [ ]:
for filepath in glob('./clean_texts/*.txt'):
    id = int(splitext(basename(filepath))[0])
    os.rename(filepath, edition_list.iloc[id-1]['title']+'_'+basename(filepath))